import type { NextPage } from "next";
import Head from "next/head";
import { Container, Title, Space, TextInput, Grid, Text, Group, NumberInput, Popover } from "@mantine/core";
import { DatePicker } from "@mantine/dates";
import { useMediaQuery } from "@mantine/hooks";
import InfoIcon from "../components/InfoIcon";

const Home: NextPage = () => {
	const breakMobile = useMediaQuery("(max-width: 480px)");

	return (
		<>
			<Head>
				<title>Rent vs. Buy Calculator</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container size={1420} px={16}>
				<Grid>
					<Grid.Col sm={12} md={4}>
						<Title order={1}>Income</Title>
						<TextInput placeholder='Input Text' label='Annual Gross Income' />
						<TextInput placeholder='Input Text' label='Annual Income Tax Rate' />
						<TextInput placeholder='Input Text' label='Annual Gross Income Growth Rate' />
						<TextInput placeholder='Input Text' label='Annual Non-Housing Expenses' />
						<TextInput placeholder='Input Text' label='Current Investments and Savings' />
						<TextInput placeholder='Input Text' label='Annual Investment Return Rate' />
						<TextInput placeholder='Input Text' label='Annual Inflation Rate' />
						<Space h={48} />
						<NumberInput
							hideControls
							label={
								<>
									{"Estimated Stay Duration in Years"}
									<InfoIcon content='This is an example of a popover on an InfoIcon.'></InfoIcon>
								</>
							}
							size={breakMobile ? "xs" : "sm"}
							defaultValue={10}
							min={1}
							max={100}
							precision={0}
						/>
						<DatePicker
							placeholder='Pick date'
							label='Start Date'
							size={breakMobile ? "xs" : "sm"}
							inputFormat='MM/DD/YYYY'
							defaultValue={new Date()}
						/>
						<NumberInput
							hideControls
							label='Payments per Year'
							size={breakMobile ? "xs" : "sm"}
							defaultValue={12}
							min={1}
							max={365}
							precision={0}
						/>
					</Grid.Col>
					<Grid.Col sm={12} md={4}>
						<Title order={1}>Buy</Title>
					</Grid.Col>
					<Grid.Col sm={12} md={4}>
						<Title order={1}>Rent</Title>
					</Grid.Col>
				</Grid>
				<Title order={1}>Result</Title>
				<Grid>
					<Grid.Col sm={12} md={4}>
						<Group position='apart'>
							<Text size='md'>Default text</Text>
							<Text size='md'>Default text</Text>
						</Group>
					</Grid.Col>
					<Grid.Col sm={12} md={4}></Grid.Col>
					<Grid.Col sm={12} md={4}></Grid.Col>
				</Grid>
				<Title order={1}>Amoritization Schedule</Title>
			</Container>
		</>
	);
};

export default Home;
