import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import { Container, Title, Space, TextInput, Grid, Text, Group, NumberInput, SegmentedControl } from "@mantine/core";
import { DatePicker } from "@mantine/dates";
import { useMediaQuery } from "@mantine/hooks";
import InfoIcon from "../components/InfoIcon";

const Home: NextPage = () => {
	const [incomeNet, setIncomeNet] = useState("gross");
	const breakMobile = useMediaQuery("(max-width: 480px)");

	return (
		<>
			<Head>
				<title>Rent vs. Buy Calculator</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Container size={1420} px={16}>
				<Grid>
					<Grid.Col sm={12} md={4}>
						<Title order={1}>Income</Title>
						<NumberInput
							hideControls
							label={
								<div style={{ display: "flex", justifyContent: "space-between", width: "100%" }}>
									<div style={{ display: "flex", alignItems: "center", marginTop: "10px" }}>
										{incomeNet == "gross" ? "Annual Gross Income" : "Annual Net Income"}
										<InfoIcon content='InfoIcon.'></InfoIcon>
									</div>
									<div style={{ width: "auto" }}>
										<SegmentedControl
											data={[
												{ label: "GROSS", value: "gross" },
												{ label: "NET", value: "net" },
											]}
											size={"xs"}
											value={incomeNet}
											onChange={setIncomeNet}
										/>
									</div>
								</div>
							}
							size={breakMobile ? "xs" : "sm"}
							icon={<Text size={breakMobile ? "xs" : "sm"}>$</Text>}
							defaultValue={50000}
							parser={(value) => value?.replace(/\$\s?|(,*)/g, "")}
							formatter={(value) => (!Number.isNaN(parseFloat(value)) ? `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ",") : "")}
							min={0}
							precision={2}
							onFocus={(value) => {
								console.log("onFocus");
							}}
						/>
						<NumberInput
							hideControls
							label={
								<>
									{"Annual Income Tax Rate"}
									<InfoIcon content='InfoIcon.'></InfoIcon>
								</>
							}
							size={breakMobile ? "xs" : "sm"}
							defaultValue={23}
							rightSection={
								<Text size={breakMobile ? "xs" : "sm"} className={"mantine-NumberInput-icon"}>
									%
								</Text>
							}
							min={0}
							max={100}
							precision={2}
						/>
						<TextInput placeholder='Input Text' label='Annual Income Tax Rate' />
						<TextInput placeholder='Input Text' label='Annual Gross Income Growth Rate' />
						<TextInput placeholder='Input Text' label='Annual Non-Housing Expenses' />
						<TextInput placeholder='Input Text' label='Current Investments and Savings' />
						<TextInput placeholder='Input Text' label='Annual Investment Return Rate' />
						<TextInput placeholder='Input Text' label='Annual Inflation Rate' />
						<Space h={48} />
						<NumberInput
							hideControls
							label={
								<>
									{"Estimated Stay Duration in Years"}
									<InfoIcon content='InfoIcon.'></InfoIcon>
								</>
							}
							size={breakMobile ? "xs" : "sm"}
							defaultValue={10}
							min={1}
							max={100}
							precision={0}
						/>
						<DatePicker
							placeholder='Pick date'
							label='Start Date'
							size={breakMobile ? "xs" : "sm"}
							inputFormat='MM/DD/YYYY'
							defaultValue={new Date()}
						/>
						<NumberInput
							hideControls
							label='Payments per Year'
							size={breakMobile ? "xs" : "sm"}
							defaultValue={12}
							onBlur={(value) => (value ? value : (value = "12"))}
							min={1}
							max={365}
							precision={0}
						/>
					</Grid.Col>
					<Grid.Col sm={12} md={4}>
						<Title order={1}>Buy</Title>
					</Grid.Col>
					<Grid.Col sm={12} md={4}>
						<Title order={1}>Rent</Title>
					</Grid.Col>
				</Grid>
				<Title order={1}>Result</Title>
				<Grid>
					<Grid.Col sm={12} md={4}>
						<Group position='apart'>
							<Text size='md'>Default text</Text>
							<Text size='md'>Default text</Text>
						</Group>
					</Grid.Col>
					<Grid.Col sm={12} md={4}></Grid.Col>
					<Grid.Col sm={12} md={4}></Grid.Col>
				</Grid>
				<Title order={1}>Amoritization Schedule</Title>
			</Container>
		</>
	);
};

export default Home;
